version: "3.5"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=shortinho
      - POSTGRES_DB=shortinho
      - POSTGRES_PASSWORD=shortinho
    networks:
      - shortinho
networks:
  shortinho:
    name: shortinho
